# Básico sobre Aprendizado de Máquina

Contrução de uma Perceptron para prever as saídas da função OU: {(0,0),(1,0),(0,1),(1,1)} -> {0,1}.
A função OU recebe um par ordenado de entrada e retorna o valor 1 se, e somente se, ao menos uma das entradas do par ordenado for 1.

In [110]:
import numpy as np

In [111]:
inputs = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]])
bias = np.array(4*[-1]).reshape(4,1)
targets=np.array([0,1,1,1])

In [112]:
inputs_bias = np.concatenate((inputs,bias),axis=1)
inputs_bias

array([[ 0,  0, -1],
       [ 1,  0, -1],
       [ 0,  1, -1],
       [ 1,  1, -1]])

In [113]:
targets = np.array([[0],[1],[1],[1]])

In [114]:
weights = np.random.rand(3,1) *.1 -.05
weights

array([[ 0.02343859],
       [ 0.00428136],
       [-0.03883385]])

In [115]:
#taxa de aprendizado
eta = 0.2 #/usualmente 0.1 to 0.4

In [116]:
#função de ativação
def activation(x,y): 
    return 1 if np.inner(x,y) > 0 else 0

In [117]:
epochs = 10
n = inputs.shape[0]

In [118]:
#Treinamento do perceptron
for j in range(epochs):
    for i in range(n):
        output = activation(inputs_bias[i],weights[:,0])
        weights[:,0] += eta *( targets[i][0] - output )* inputs_bias[i]

In [119]:
#Pesos após o treinamento
weights

array([[0.22343859],
       [0.20428136],
       [0.16116615]])

In [120]:
#Testando as saidas após o treinamento
test_output = []
for i in range(4):
    test_output.append(activation(inputs_bias[i],weights[:,0]))
test_output

[0, 1, 1, 1]