# Básico sobre Aprendizado de Máquina

Contrução de uma Perceptron para prever as saídas da função OU: {(0,0),(1,0),(0,1),(1,1)} -> {0,1}.
A função OU recebe um par ordenado de entrada e retorna o valor 1 se, e somente se, ao menos uma das entradas do par ordenado for 1.


In [57]:
import numpy as np

In [58]:
inputs = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]])
bias = np.array(4*[-1]).reshape(4,1)
targets=np.array([0,1,1,1])
inputs = np.concatenate((inputs,bias),axis=1)
inputs


array([[ 0,  0, -1],
       [ 1,  0, -1],
       [ 0,  1, -1],
       [ 1,  1, -1]])

In [59]:
targets=np.array([[0],[1],[1],[1]])
bias = np.array(4*[-1]).reshape(4,1)
bias

array([[-1],
       [-1],
       [-1],
       [-1]])

In [60]:
weights = np.random.rand(3,1) *.1 -.05
weights

array([[ 0.02787743],
       [ 0.03313953],
       [-0.01361803]])

In [62]:
learning_rate = 0.2 #/usualmente 0.1 to 0.4

In [63]:
def activation(x,y): 
    return 1 if np.inner(x,y) > 0 else 0

In [70]:
epochs = 1
n = inputs.shape[0]

In [71]:
for j in range(epochs):
    for i in range(n):
        output = activation(inputs[i],weights[:,0])
        weights[:,0] += learning_rate *( targets[i][0] - output )* inputs[i]

    

In [72]:
weights

array([[0.22787743],
       [0.23313953],
       [0.18638197]])

In [73]:
test = []

In [74]:
for i in range(4):
    test.append(activation(inputs[i],weights[:,0]))

In [75]:
test

[0, 1, 1, 1]